var products =[{
    "id":0,
    "title":"-- Select Anyone --",
    "price":"",
    "description":"",
    "brand":"",
    "image":"/No_Image.png",
},{
    // men
    "id":1,
    "title":"Meraas Odhni - Black",
    "price":3600,
    "description":"Meraas Odhni Made from Cotton Silk, Features Beautiful Urdu Poetry by Allama Iqbal Printed Throughout.",
    "brand":"Van Heusen",
    "image":"https://www.shopmanto.com/cdn/shop/files/13_01383df8-d36f-4746-b4bc-93a5c649c15b.jpg?v=1717707992&width=320",
},{
    "id":2,
    "title":"Cloud White - Lucknow (Men)",
    "price":8500,
    "description":"Manto Men's Solid Wash-n-wear Lucknow Kurta & Pajama Set. Smooth, Breezy & Breathable texture made from BREEZE® Technology Butter Fabric.",
    "brand":"Van Heusen",
    "image":"https://www.shopmanto.com/cdn/shop/files/1_eef20cb5-f202-40a3-be47-f63ba224e7da.jpg?v=1711950205&width=400",
},{
    "id":3,
    "title":"Deep Teal - Sherwani ",
    "price":9500,
    "description":"Manto Men's Solid Wash-n-wear Sherwani Kurta & Pajama Set. Smooth, Breezy & Breathable texture made from BREEZE® Technology Butter Fabric",
    "brand":"Van Heusen",
    "image":"https://i.pinimg.com/474x/f1/7e/5c/f17e5c99c104e8f77e77734f0ecfe394.jpg",
},{
    "id":4,
    "title":"Riwayat Vasket - Green",
    "price":.7500,
    "description":"Men’s green khaddar waistcoat, made from 100% Cotton. Featuring calligraphy of Urdu letters.",
    "brand":"Zara",
    "image":"https://www.shopmanto.com/cdn/shop/files/417_e4b92997-6a58-44ae-a8d7-6cbcb20c33b0.jpg?crop=center&height=540&v=1735209365&width=360",
},{
    "id":5,
    "title":"Midnight Blue - Lucknow",
    "price":8500,
    "description":"Manto Men's Solid Wash-n-wear Lucknow Kurta & Pajama Set. Smooth, Breezy & Breathable texture made from BREEZE® Technology Butter Fabric.",
"brand":"Zara",
    "image":"https://www.shopmanto.com/cdn/shop/files/421.jpg?v=1714323302",
},{
    "id":6,
    "title":"Zamana Overshirt - Ash Blue",
    "price":7500,
    "description":"Unisex Printed Zamana Overshirt, Made from Premium Khaddar, is Perfect Layer for Winter. Featuring the Powerful Words of Jigar Murad Abadi..",
    "brand":"Zara",
    "image":"https://www.shopmanto.com/cdn/shop/files/DSC_5359.jpg?crop=center&height=540&v=1702884356&width=360",
},{
    "id":7,
    "title":"Emerald Green - Lucknow",
    "price":8500,
    "description":"Manto Men's Solid Wash-n-wear Lucknow Kurta & Pajama Set. Smooth, Breezy & Breathable texture made from BREEZE® Technology Butter Fabric.",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/13_7bf3c63c-b99a-4cc3-b5db-25f0b77b6a11.jpg?crop=center&height=540&v=1711029369&width=360",
},{
    "id":8,
    "title":"Safar Shirt - Charcoal Grey",
    "price":3950,
    "description":"Unisex Loose Fit Cuban Style Half Sleeves Button Down Shirt Featuring the Words of Nida Fazli,",
"brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/350.jpg?crop=center&height=540&v=1712304619&width=360",
},{
    "id":9,
    "title":"Riwayat Vasket - Purple",
    "price":7500,
    "description":"Men’s Purple khaddar waistcoat, made from 100% Cotton. Featuring calligraphy of Urdu letters.",
"brand":"outfitters",    "image":"https://www.shopmanto.com/cdn/shop/files/412_df47c60b-3090-424e-9448-a74df20fd55a.jpg?v=1735209760&width=400",
},{
    "id":10,
    "title":"Bagh-e-Mughal Overshirt - Brown & Green",
    "price":8200,
    "description":"Unisex Khaddar Overshirt, made from 100% cotton, features Urdu calligraphy of poetry by Haider Ali Aatish.",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/377.jpg?v=1735200480&width=400",
},{
    // women
    "id":11,
    "title":"SEHER CO-ORD SET BEIGE AND GREEN",
    "price":9200,
    "description":"The Seher Co-ord Set, made from Soft Crepe, is a 2 Piece Set with a Long-Length Shirt and Straight Pants. This modern cut features beautiful poetry by Allama Iqbal.",
    "brand":"Van Heusen",
    "image":"https://www.shopmanto.com/cdn/shop/files/11_3da012d1-15ee-49ed-8a2b-8e9fa4af31b0.jpg?v=1722684435&width=1300",
},{
    "id":12,
    "title":"DEEP TEAL RAYA SET",
    "price":9800,
    "description":"Ultra-soft solid 2-piece matching set, a short shirt perfectly paired with a relaxed-fit shalwar. Designed to make you feel at ease without compromising on style, every day.",
    "brand":"Van Heusen",
    "image":"https://www.shopmanto.com/cdn/shop/files/5_5d7ee128-84cb-44de-bad2-6e5180b64d96.jpg?v=1736248051&width=1300",
},{
    "id":13,
    "title":"QALB SET-OLIVE GREEN",
    "price":9400,
    "description":"Printed Two Piece Soft Crepe Co-Ord Set, Featuring Random Urdu Letter Calligraphed on the Shirt. ",
    "brand":"Van Heusen",
    "image":"https://www.shopmanto.com/cdn/shop/files/1_6f645eba-9e19-4c30-9aca-a79096adea86.jpg?v=1717863530&width=1300",
},{
    "id":14,
    "title":"BULBUL CO-ORD SET BEIGE & GREEN",
    "price":9200,
    "description":"2 Piece matching khaddar set, featuring versatile fit & Urdu calligraphy of poetry by Makhdoom Mohiuddin. Pair it with your favorite odhni or dupatta to complete a look.",
    "brand":"zara",
    "image":"https://www.shopmanto.com/cdn/shop/files/13_ca56ac0a-3356-48ed-921b-19eb683093a3.jpg?v=1736968723&width=400",
},{
    "id":15,
    "title":"SHAJAR CO-ORD SET BLACK & GREEN",
    "price":9400,
    "description":"The Shajar Co-ord Set, made from Soft Crepe, is a 2 Piece Set with a Long-Length A-Line Shirt and Straight Pants. This modern cut features words like Khuwaab, Khayaal, Chandni, Shab Etc.",
    "brand":"zara",
    "image":"https://www.shopmanto.com/cdn/shop/files/10_46389d94-bb17-431e-a8f9-64fe1ada0af6.jpg?v=1722683375&width=1300",
},{
    "id":16,
    "title":"RUBBY RED RESYL SET",
    "price":8800,
    "description":"Premium Lawn Printed Two Piece Set, Featuring the Words of Nida Fazli. Available in 5 Colors with Matching Separate Dupattas.",
    "brand":"Zara",
    "image":"https://www.shopmanto.com/cdn/shop/products/DSC02303.jpg?crop=center&height=540&v=1680857607&width=360",
},{
    "id":17,
    "title":"SURAJ SHRUG SHADES OF DAWN",
    "price":6950,
    "description":"Printed Outerwear Shrug Made from Soft Crepe Featureing Calligraphy of Urdu Letters.",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/17_041543ef-e870-480b-9376-e4ea640ef4fc.jpg?v=1711690780&width=1300",
},{
    "id":18,
    "title":"BREEZE CO-ORD SET PINK",
    "price":9400,
    "description":"A 2-Piece solid co-ord set made from BREEZE® Technology Butter Fabric. With a Loose-Fit Paneled Shirt, Straight Pants, this Smooth, Breezy Breathable Textured set is perfect for an comfortable yet elegant look",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/48_66932550-9cf6-4d31-a0d4-2154b2770e02.jpg?crop=center&height=540&v=1736146220&width=360",
},{
    "id":19,
    "title":"MIDNIGHT BLUE MIRA SET",
    "price":9800,
    "description":"Solid Two Piece Co-Ord Set made from Premium Ultra Soft Wash-n-Wear. Smooth & Breathable BREEZE® Technology Butter Fabric, Available in 11 Colors!",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/438.jpg?v=1714330702&width=1300",
},{
    "id":20,
    "title":"HAYAT ANARKALI CREAM AND MINT",
    "price":6950,
    "description":"Printed Long Length Flowy Anarkali made from Premium Lawn, with Swiss Lawn Matching Separate Dupattas. Featuring the words of Makhdoom Mohiuddin, Available in 2 Colors!",
    "brand":"outfitters",
    "image":"https://www.shopmanto.com/cdn/shop/files/3_9437431a-6f37-4309-ba11-9b7f0a550aed.jpg?v=1725967898&width=400",
},{ 
    // kids
    "id":21,
    "title":"HAYAT ANARKALI CREAM AND MINT",
    "price":8000,
    "description":"'Top Fabric: Digital Printed Lawn Stitched Top, Bottom Fabric: Cotton stitched Dyed Trouser, DIGITAL PRINTED SUIT, DYED TROUSER, STITCHED, 2",
    "brand":"Van Heusen",
    "image":"https://www.libasejamila.com/wp-content/uploads/2021/06/girls-dresses-Pakistani-21-scaled.jpg",
},{
    "id":22,
    "title":"Urooj Kurta - Plum",
    "price":7950,
    "description":"'Top: Soft Cotton Kameez with Heavy Embroidery work and Piping on Daman., Bottom: Soft Cotton Trouser with Embroidery'",
    "brand":"Van Heusen",
    "image":"https://www.libasejamila.com/wp-content/uploads/2022/07/Pakistani-kids-clothes-2.jpg",
},{
    "id":23,
    "title":"Dilkash Kurta ",
    "price":5800,
    "description":"'Soft Cotton Kameez and Piping on Daman., Bottom: Soft Cotton Trouser '",
    "brand":"Zara",
    "image":"https://www.libasejamila.com/wp-content/uploads/2022/03/kids-Pakistani-clothes-5-scaled.jpg",
},{
    "id":24,
    "title":"Naqsh Co-ord Set - Graphite & Magenta",
    "price":8400,
    "description":"Party-dress-for-Girls-, Available in 2 Colors!'",
    "brand":"Zara",
    "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQd__LHcf_DEbhMwhhB2QsKw-kVT_S4QkcFSul6jn8m8GEsCNaYIZ45amAO_YYAnD96Yjg&usqp=CAU",
},{
    "id":25,
    "title":"Kalidaar Co-Ord - Teal Blue",
    "price":4400,
    "description":"'Party-dress-for-Girls-5-'",
    "brand":"outfitters",
    "image":"https://www.libasejamila.com/wp-content/uploads/2023/06/Party-dress-for-Girls-5-scaled-400x600.jpg",
},{
    "id":26,
    "title":"Gulnaar Co-Ord Set ",
    "price":5800,
    "description":"'Soft Cotton Kameez with Heavy Embroidery work and Piping on Daman., Bottom: Soft Cotton Trouser with Embroidery. '",
    "brand":"outfitters",
    "image":"https://www.ansabjahangirstudio.com/images/thumbs/0008132_gradient-oasis-girl_700.jpeg",
}]